### PR TITLE
Added replay button

### PR DESCRIPTION
**Pull request by remi59800**

### CODE REVIEW

**Review by n-faycel — DISMISSED** [review]
ok

**Review by LuigiMenez — DISMISSED** [review]
Ok for me,

**Review by LoicBrassart — DISMISSED** [review]
Saw no Evil

**Review by n-faycel — APPROVED** [review]
ok for me

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
Still no Evil

**Pull request merged**
