### PR TITLE
style victory page

### PR DESCRIPTION
**Pull request by FrancoisSalmon**

### CODE REVIEW

**Review by Gonaline — DISMISSED** [review]
ok

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Review by LoicBrassart — DISMISSED** [review]
Saw no Evil

**Review by Gonaline — APPROVED** [review]
ok

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
