### PR TITLE
dice animation + position

### PR DESCRIPTION
**Pull request by ValentinCop**

### CODE REVIEW

**Review by FrancoisSalmon — DISMISSED** [review]
ok for  me

**Review by LuigiMenez — CHANGES_REQUESTED** [review]
Change CSS

**Review by FrancoisSalmon — APPROVED** [review]
ok for me

**Review by LuigiMenez — APPROVED** [review]
Ok for me

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
