### PR TITLE
025 responsiveglobal

### PR DESCRIPTION
**Pull request by n-faycel**

### CODE REVIEW

**Review by Gonaline — DISMISSED** [review]

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Review by LoicBrassart — DISMISSED** [review]
Saw no Evil

**Review by Gonaline — APPROVED** [review]
ok

**Review by LuigiMenez — APPROVED** [review]
Ok for me

**Review by LoicBrassart — APPROVED** [review]
Saw no Evil

**Pull request merged**
