### PR TITLE
sprint 5 merge (bis bis)

### PR DESCRIPTION
**Pull request by ValentinCop**

### CODE REVIEW

**Review by camillaume — DISMISSED** [review]
OK

**Review by remi59800 — DISMISSED** [review]
ok

**Review by n-faycel — DISMISSED** [review]
ok for me !!!!

**Review by FrancoisSalmon — DISMISSED** [review]
ok for me

**Review by Gonaline — DISMISSED** [review]
ok

**Review by FrancoisSalmon — APPROVED** [review]
ok

**Review by Gonaline — APPROVED** [review]
ok

**Review by camillaume — APPROVED** [review]
OK

**Review by remi59800 — APPROVED** [review]
ok

**Review by FrancoisSalmon — APPROVED** [review]

**Review by n-faycel — APPROVED** [review]
ok 👍

**Pull request merged**
