### PR TITLE
After clhoosing an answer : Changing colors to grey for the wrong ans…

### PR DESCRIPTION
**Pull request by camillaume**
…wers and displaying the right one in green

### CODE REVIEW

**Review by LoicBrassart — CHANGES_REQUESTED** [review]
So you created a `finished` state which is `true` when `clickable` is `false` and `false` when `clickable` is `true`...
... Why? Use `!clickable` ?

**Review by Gonaline — APPROVED** [review]
ok for me

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
No more Evil

**Pull request merged**
