### PR TITLE
Merging dev to master for the pres of the 29/04

### PR DESCRIPTION
**Pull request by camillaume**

### CODE REVIEW

**Review by FrancoisSalmon — DISMISSED** [review]
ok for me

**Review by Gonaline — DISMISSED** [review]
ok for me

**Review by remi59800 — DISMISSED** [review]
ok for me

**Review by ValentinCop — DISMISSED** [review]
oki doki

**Review by n-faycel — DISMISSED** [review]
ok 🤙

**Review by FrancoisSalmon — APPROVED** [review]
ok for me

**Review by remi59800 — APPROVED** [review]
ok for me

**Review by Gonaline — APPROVED** [review]
ok for me

**Review by ValentinCop — APPROVED** [review]
oki doki

**Review by n-faycel — APPROVED** [review]
ok 🤙👌

**Review by ValentinCop — APPROVED** [review]
oki doki

**Review by LuigiMenez — APPROVED** [review]
ok

**Pull request merged**
